# Generated by Django 4.1.1 on 2022-10-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="Введите имя пользователя до 60 знаков",
                max_length=60,
                verbose_name="Имя",
            ),
        ),
    ]
