# Generated by Django 4.1.1 on 2022-10-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_location_lat_alter_location_lng_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
